#if !canImport(ObjectiveC)
    import XCTest

    extension ElasticLogTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__ElasticLogTests = [
            ("testExample", testExample),
            ("testTCPExample", testTCPExample),
            ("testUDPExample", testUDPExample),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(ElasticLogTests.__allTests__ElasticLogTests),
        ]
    }
#endif
